name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.33.0
          run_install: false

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile

      # This enables task distribution via Nx Cloud.
      - run: pnpm exec nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="typecheck"

      # Prepend any command with "nx record --" to record its logs to Nx Cloud
      - if: github.event_name == 'pull_request'
        run: pnpm exec nx record -- pnpm exec nx format:check --base="origin/${{ github.base_ref }}" --head="${{ github.sha }}"
      - if: github.event_name == 'push'
        run: pnpm exec nx record -- pnpm exec nx format:check --base="${{ github.event.before }}" --head="${{ github.sha }}"
      - run: pnpm exec nx run-many -t lint build typecheck --outputStyle=static
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      - run: pnpm exec nx fix-ci
        if: always()
